# Tabular Data

What does data look like? For most people, the first image that comes to mind is a spreadsheet, where each row represents something for which information is being measured and each column a type of measurement. This stereotype exists for a reason; many real-world data sets can indeed be organized this way. Data that can be represented using rows and columns is called **tabular data**. The rows are also called **observations** or **records**,  while the columns are called **variables** or **fields**. The different terms reflect the diverse communities within data science, and their origins are summarized in the table below.

|                     | Rows           | Columns     |
|---------------------|----------------|-------------|
| Statisticians       | "observations" | "variables" |
| Computer Scientists | "records"      | "fields"    |

The table below is an example of a
data set that can be represented in tabular form.
This is a sample of user profiles in the
San Francisco Bay Area from the online dating website
OKCupid. In this case, each observation is an OKCupid user, and the variables include age, body type, height, and
(relationship) status. Although a
data table can contain values of all types, the
values within a column are typically all of the same
type---the age and height columns store
numbers, while the body type and
status columns store strings. Some values may be missing, such as body type for the first user
and diet for the second.

| age | body type |        diet       | ... | smokes | height | status |
|-----|-----------|-------------------|-----|--------|--------|--------|
| 31  |           | mostly vegetarian | ... |   no   |   67   | single |
| 31  |  average  |                   | ... |   no   |   66   | single |
| 43  |   curvy   |                   | ... | trying to quit | 65 | single |
| ... |    ...    |       ...         | ... |  ...   |  ...   | ... |
| 60  |    fit    |                   | ... |   no   |   57   | single |



# Introduction to Pandas

Tabular data is essential for doing data science. But a structure for tabular data is not built into Python, so we need to import a library. That library is [Pandas](https://pandas.pydata.org/), which essentially does one thing---define a data structure called a `DataFrame` for storing tabular data. But this data structure is so fundamental to data science that importing `pandas` is the very first line of many Colab notebooks and Python scripts.

Let's import `pandas`. The standard abbreviation for Pandas is `pd`.

In [1]:
import pandas as pd

A Pandas `DataFrame` is optimized for storing tabular data; for example, it uses the fact that the values within a column are all the same type to save memory and speed up computations.

Many data sets are stored as files on disk, such as in **comma-separated values (CSV)** files. How do we get data into a `pandas` `DataFrame`? Pandas provides a function called `read_csv()` for reading in files in CSV format.

## Reading in Data from a URL

If the data file already lives on the Internet, then you can simply pass in the URL to `read_csv()`.

In [2]:
# Read in the OKCupid data set using the Pandas `read_csv` function.
df_okcupid = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/okcupid.csv")

In [3]:
# Display the first few and last few rows and columns
df_okcupid.head()

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,height,status
0,31,NaN,mostly vegetarian,socially,sometimes,graduated from college/university,"75% nice, 45% shy, 80% stubborn, 100% charming...",i'm a new nurse. it rules.,"multiple-choice questions, dancing.",it depends on the people.,...,"san francisco, california",might want kids,gay,likes cats,buddhism,f,taurus and it&rsquo;s fun to think about,no,67.0,single
1,25,average,NaN,socially,NaN,working on college/university,"i like trees, spending long periods of time co...","studying landscape horticulture, beekeeping, g...","wasting time, making breakfast, nesting",i have a lot of freckles,...,"oakland, california",NaN,gay,NaN,NaN,m,sagittarius and it&rsquo;s fun to think about,no,66.0,single
2,43,curvy,NaN,rarely,never,graduated from masters program,NaN,NaN,NaN,NaN,...,"san francisco, california",has a kid,straight,likes dogs and has cats,other and laughing about it,f,leo and it&rsquo;s fun to think about,trying to quit,65.0,single
3,31,average,NaN,socially,never,NaN,"i am a seeker of laughs ,music ,magick good pe...",i strive to live life to the fullest and to tr...,i am good at my magic and weaving a world of i...,i am guessing y'all would notice my jewelry an...,...,"san francisco, california",doesn&rsquo;t want kids,gay,NaN,other and very serious about it,m,capricorn and it&rsquo;s fun to think about,trying to quit,70.0,single
4,34,NaN,NaN,socially,NaN,graduated from ph.d program,i've just moved here from london after finishi...,i'm doing a postdoc in psychology at stanford,NaN,NaN,...,"san francisco, california",NaN,gay,NaN,NaN,m,cancer but it doesn&rsquo;t matter,NaN,71.0,single


Notice above how missing values are represented in a `pandas` `DataFrame`. Each missing value is represented by a `NaN`, which is short for "not a number". As we will see, most `pandas` operations simply ignore `NaN` values.

The `info` method returns some information about the data frame.

In [4]:
df_okcupid.info(verbose = False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Columns: 31 entries, age to status
dtypes: float64(1), int64(2), object(28)
memory usage: 726.7+ KB


The `shape` attribute returns the number of (rows, columns).

In [5]:
df_okcupid.shape

(3000, 31)

## Reading in Data from a File

If you instead want to read in a data file on your computer, you can pass in the path to the file (e.g., `"/home/data/mydata.csv"`) to `read_csv()`.

There's just one catch. Colab is a cloud service; it can't read files on your computer. In order to read in a data file from Colab, you have to upload the file to the Colab file system.

Instructions:

1. Click on the folder icon in the left toolbar. This will open up a pane that allows you to interact with the Colab file system.
2. Click on the upload icon and find the file that you want to upload.

Now the data file is on the Colab file system, so we can read it in using `read_csv()`. By default, files get uploaded to `/content/`. If you get a `FileNotFoundError`, double check where you uploaded the file.

In [6]:
# You can practice uploading any CSV file that is on your computer
# If you want, you can download the okcupid.csv file to your computer
# You can download it from: https://github.com/kevindavisross/data301/tree/main/data
# Once it is on your computer, you can upload the file to Colab using the instructions above
# Now you can read in the OK Cupid data set using the Pandas `read_csv` function.

# df_okcupid = pd.read_csv("/content/okcupid.csv")

# df_okcupid

# Rows and Observational Units

Recall that the rows of a tabular data set represent observations (or records). Whenever you encounter a new (tabular) data
set, the first question you should ask yourself is

> "What is the observational unit?"

In other words, what does each row of the
`DataFrame` represent? In the case of
the OKCupid data set in the previous section, the observational unit was clearly an OKCupid user. But it is not always so obvious what the observational unit is.

For example, consider the [Framingham Heart Study](https://www.framinghamheartstudy.org/fhs-about/) data set, which is available at https://raw.githubusercontent.com/kevindavisross/data301/main/data/framingham_long.csv.
This data comes from a study of men and women in
the town of Framingham, Massachusetts, which has enrolled
thousands of patients since it began in 1948 and is still ongoing. The goal of the study is to identify risk factors for cardivascular disease (CVD) by following the subjects over time. The data set that we will analyze was collected on 4,434 subjects between 1956 and 1968. A description of the data set is available [here](https://biolincc.nhlbi.nih.gov/media/teachingstudies/FHS_Teaching_Longitudinal_Data_Documentation_2021a.pdf).

You might guess that the observational unit is a subject. Let's see if that guess is correct.

In [7]:
import pandas as pd

In [8]:
df_framingham = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/framingham_long.csv")
df_framingham

,RANDID,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,...,CVD,HYPERTEN,TIMEAP,TIMEMI,TIMEMIFC,TIMECHD,TIMESTRK,TIMECVD,TIMEDTH,TIMEHYP
0,2448,1,195.0,39,106.0,70.0,0,0.0,26.97,0,...,1,0,8766,6438,6438,6438,8766,6438,8766,8766
1,2448,1,209.0,52,121.0,66.0,0,0.0,NaN,0,...,1,0,8766,6438,6438,6438,8766,6438,8766,8766
2,6238,2,250.0,46,121.0,81.0,0,0.0,28.73,0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766
3,6238,2,260.0,52,105.0,69.5,0,0.0,29.43,0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766
4,6238,2,237.0,58,108.0,66.0,0,0.0,28.50,0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11622,9998212,1,173.0,46,126.0,82.0,0,0.0,19.17,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,0
11623,9998212,1,153.0,52,143.0,89.0,0,0.0,25.74,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,0
11624,9999312,2,196.0,39,133.0,86.0,1,30.0,20.91,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,4201
11625,9999312,2,240.0,46,138.0,79.0,1,20.0,26.39,0,...,0,1,8766,8766,8766,8766,8766,8766,8766,4201


Each `RANDID` corresponds to a unique subject in the study, but each subject appears multiple times in the data set. That is because this is a *longitudinal* study; each subject was measured at multiple points during their lifetime. So the observational unit in the Framingham Heart Study data set is a _measurement_ of a subject at a point in time.

If there is a variable or a set of variables in the data set that uniquely identifies the observational unit, then it is customary to make those variables the **index** of the `DataFrame`. In the Framingham data set, `RANDID` and `TIME` uniquely identify the observational unit, so we move these columns to the index. (Notice that we specify `inplace=True` so that `.set_index()` modifies the existing `DataFrame` rather than returning a new one.)

In [9]:
df_framingham.set_index(["RANDID", "TIME"], inplace=True)
df_framingham

SEX  TOTCHOL  AGE  SYSBP  DIABP  CURSMOKE  CIGPDAY    BMI  \
RANDID  TIME                                                              
2448    0       1    195.0   39  106.0   70.0         0      0.0  26.97   
        4628    1    209.0   52  121.0   66.0         0      0.0    NaN   
6238    0       2    250.0   46  121.0   81.0         0      0.0  28.73   
        2156    2    260.0   52  105.0   69.5         0      0.0  29.43   
        4344    2    237.0   58  108.0   66.0         0      0.0  28.50   
...           ...      ...  ...    ...    ...       ...      ...    ...   
9998212 2333    1    173.0   46  126.0   82.0         0      0.0  19.17   
        4538    1    153.0   52  143.0   89.0         0      0.0  25.74   
9999312 0       2    196.0   39  133.0   86.0         1     30.0  20.91   
        2390    2    240.0   46  138.0   79.0         1     20.0  26.39   
        4201    2      NaN   50  147.0   96.0         1     10.0  24.19   

              DIABETES  BPMEDS  ...  CVD  HYPERTEN  TIMEAP  TIMEMI  TIMEMIFC  \
RANDID  TIME                    ...                                            
2448    0            0     0.0  ...    1         0    8766    6438      6438   
        4628         0     0.0  ...    1         0    8766    6438      6438   
6238    0            0     0.0  ...    0         0    8766    8766      8766   
        2156         0     0.0  ...    0         0    8766    8766      8766   
        4344         0     0.0  ...    0         0    8766    8766      8766   
...                ...     ...  ...  ...       ...     ...     ...       ...   
9998212 2333         0     0.0  ...    0         1    8766    8766      8766   
        4538         0     0.0  ...    0         1    8766    8766      8766   
9999312 0            0     0.0  ...    0         1    8766    8766      8766   
        2390         0     0.0  ...    0         1    8766    8766      8766   
        4201         0     0.0  ...    0         1    8766    8766      8766   

              TIMECHD  TIMESTRK  TIMECVD  TIMEDTH  TIMEHYP  
RANDID  TIME                                                
2448    0        6438      8766     6438     8766     8766  
        4628     6438      8766     6438     8766     8766  
6238    0        8766      8766     8766     8766     8766  
        2156     8766      8766     8766     8766     8766  
        4344     8766      8766     8766     8766     8766  
...               ...       ...      ...      ...      ...  
9998212 2333     8766      8766     8766     8766        0  
        4538     8766      8766     8766     8766        0  
9999312 0        8766      8766     8766     8766     4201  
        2390     8766      8766     8766     8766     4201  
        4201     8766      8766     8766     8766     4201  

[11627 rows x 37 columns]

## Selecting Rows

We can select an individual row from a `DataFrame` using its label in the index. For example, the fourth row in the Framingham data set above has `(RANDID, TIME)` label (6238, 2156). The `.loc` attribute of the `DataFrame` is used to select a row by its label.

In [10]:
row = df_framingham.loc[(6238, 2156)]
row

SEX            2.00
TOTCHOL      260.00
AGE           52.00
SYSBP        105.00
DIABP         69.50
CURSMOKE       0.00
CIGPDAY        0.00
BMI           29.43
DIABETES       0.00
BPMEDS         0.00
HEARTRTE      80.00
GLUCOSE       86.00
educ           2.00
PREVCHD        0.00
PREVAP         0.00
PREVMI         0.00
PREVSTRK       0.00
PREVHYP        0.00
PERIOD         2.00
HDLC            NaN
LDLC            NaN
DEATH          0.00
ANGINA         0.00
HOSPMI         0.00
MI_FCHD        0.00
ANYCHD         0.00
STROKE         0.00
CVD            0.00
HYPERTEN       0.00
TIMEAP      8766.00
TIMEMI      8766.00
TIMEMIFC    8766.00
TIMECHD     8766.00
TIMESTRK    8766.00
TIMECVD     8766.00
TIMEDTH     8766.00
TIMEHYP     8766.00
Name: (6238, 2156), dtype: float64

We can also select a row by its position using the `.iloc` attribute. Keeping in mind that Python uses zero-based indexing so the first row is actually row 0, the fourth row could also be extracted as:

In [11]:
df_framingham.iloc[3]

SEX            2.00
TOTCHOL      260.00
AGE           52.00
SYSBP        105.00
DIABP         69.50
CURSMOKE       0.00
CIGPDAY        0.00
BMI           29.43
DIABETES       0.00
BPMEDS         0.00
HEARTRTE      80.00
GLUCOSE       86.00
educ           2.00
PREVCHD        0.00
PREVAP         0.00
PREVMI         0.00
PREVSTRK       0.00
PREVHYP        0.00
PERIOD         2.00
HDLC            NaN
LDLC            NaN
DEATH          0.00
ANGINA         0.00
HOSPMI         0.00
MI_FCHD        0.00
ANYCHD         0.00
STROKE         0.00
CVD            0.00
HYPERTEN       0.00
TIMEAP      8766.00
TIMEMI      8766.00
TIMEMIFC    8766.00
TIMECHD     8766.00
TIMESTRK    8766.00
TIMECVD     8766.00
TIMEDTH     8766.00
TIMEHYP     8766.00
Name: (6238, 2156), dtype: float64

Notice that a single row from a `DataFrame` is no longer a `DataFrame` but a different data structure, called a `Series`.

In [12]:
type(row)

pandas.core.series.Series

We can also select multiple rows by passing a _list_ of labels or positions to `.loc` and `.iloc`, respectively.

In [13]:
rows = df_framingham.loc[[(2448, 4628), (6238, 2156)]]
rows

,,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,...,CVD,HYPERTEN,TIMEAP,TIMEMI,TIMEMIFC,TIMECHD,TIMESTRK,TIMECVD,TIMEDTH,TIMEHYP
RANDID,TIME,,,,,,,,,,,,,,,,,,,,,
2448,4628,1,209.0,52,121.0,66.0,0,0.0,NaN,0,0.0,...,1,0,8766,6438,6438,6438,8766,6438,8766,8766
6238,2156,2,260.0,52,105.0,69.5,0,0.0,29.43,0,0.0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766


In [14]:
df_framingham.iloc[[1, 3]]

,,SEX,TOTCHOL,AGE,SYSBP,DIABP,CURSMOKE,CIGPDAY,BMI,DIABETES,BPMEDS,...,CVD,HYPERTEN,TIMEAP,TIMEMI,TIMEMIFC,TIMECHD,TIMESTRK,TIMECVD,TIMEDTH,TIMEHYP
RANDID,TIME,,,,,,,,,,,,,,,,,,,,,
2448,4628,1,209.0,52,121.0,66.0,0,0.0,NaN,0,0.0,...,1,0,8766,6438,6438,6438,8766,6438,8766,8766
6238,2156,2,260.0,52,105.0,69.5,0,0.0,29.43,0,0.0,...,0,0,8766,8766,8766,8766,8766,8766,8766,8766


Notice that when we select multiple rows, we get a `DataFrame` back.

In [15]:
type(rows)

pandas.core.frame.DataFrame

A `Series` can be used to store a single observation (across multiple variables), while a `DataFrame` is used to store multiple observations (across multiple variables). We will see soon that a `Series` can also be used to store a single column (across multiple observations), so

- A `Series` stores one-dimensional data (i.e., a single row or column).
- A `DataFrame` stores two-dimensional data (i.e., both rows and columns).

If selecting consecutive rows, we can use Python's `slice` notation. For example, the code below selects all rows from the fourth row, up to (but not including) the tenth row.

In [16]:
df_framingham.iloc[3:9]

SEX  TOTCHOL  AGE  SYSBP  DIABP  CURSMOKE  CIGPDAY    BMI  \
RANDID TIME                                                              
6238   2156    2    260.0   52  105.0   69.5         0      0.0  29.43   
       4344    2    237.0   58  108.0   66.0         0      0.0  28.50   
9428   0       1    245.0   48  127.5   80.0         1     20.0  25.34   
       2199    1    283.0   54  141.0   89.0         1     30.0  25.34   
10552  0       2    225.0   61  150.0   95.0         1     30.0  28.58   
       1977    2    232.0   67  183.0  109.0         1     20.0  30.18   

             DIABETES  BPMEDS  ...  CVD  HYPERTEN  TIMEAP  TIMEMI  TIMEMIFC  \
RANDID TIME                    ...                                            
6238   2156         0     0.0  ...    0         0    8766    8766      8766   
       4344         0     0.0  ...    0         0    8766    8766      8766   
9428   0            0     0.0  ...    0         0    8766    8766      8766   
       2199         0     0.0  ...    0         0    8766    8766      8766   
10552  0            0     0.0  ...    1         1    2956    2956      2956   
       1977         0     0.0  ...    1         1    2956    2956      2956   

             TIMECHD  TIMESTRK  TIMECVD  TIMEDTH  TIMEHYP  
RANDID TIME                                                
6238   2156     8766      8766     8766     8766     8766  
       4344     8766      8766     8766     8766     8766  
9428   0        8766      8766     8766     8766     8766  
       2199     8766      8766     8766     8766     8766  
10552  0        2956      2089     2089     2956        0  
       1977     2956      2089     2089     2956        0  

[6 rows x 37 columns]

# Columns and Variables

Recall that the columns of a tabular data set represent variables (or fields). They are the measurements that we make on each observation.

As an example, let's consider the variables in the OKCupid data set.

In [17]:
import pandas as pd

In [18]:
df_okcupid = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/okcupid.csv")
df_okcupid

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,height,status
0,31,NaN,mostly vegetarian,socially,sometimes,graduated from college/university,"75% nice, 45% shy, 80% stubborn, 100% charming...",i'm a new nurse. it rules.,"multiple-choice questions, dancing.",it depends on the people.,...,"san francisco, california",might want kids,gay,likes cats,buddhism,f,taurus and it&rsquo;s fun to think about,no,67.0,single
1,25,average,NaN,socially,NaN,working on college/university,"i like trees, spending long periods of time co...","studying landscape horticulture, beekeeping, g...","wasting time, making breakfast, nesting",i have a lot of freckles,...,"oakland, california",NaN,gay,NaN,NaN,m,sagittarius and it&rsquo;s fun to think about,no,66.0,single
2,43,curvy,NaN,rarely,never,graduated from masters program,NaN,NaN,NaN,NaN,...,"san francisco, california",has a kid,straight,likes dogs and has cats,other and laughing about it,f,leo and it&rsquo;s fun to think about,trying to quit,65.0,single
3,31,average,NaN,socially,never,NaN,"i am a seeker of laughs ,music ,magick good pe...",i strive to live life to the fullest and to tr...,i am good at my magic and weaving a world of i...,i am guessing y'all would notice my jewelry an...,...,"san francisco, california",doesn&rsquo;t want kids,gay,NaN,other and very serious about it,m,capricorn and it&rsquo;s fun to think about,trying to quit,70.0,single
4,34,NaN,NaN,socially,NaN,graduated from ph.d program,i've just moved here from london after finishi...,i'm doing a postdoc in psychology at stanford,NaN,NaN,...,"san francisco, california",NaN,gay,NaN,NaN,m,cancer but it doesn&rsquo;t matter,NaN,71.0,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,24,athletic,mostly anything,socially,sometimes,graduated from college/university,recent relocatee to san francisco. i'm writing...,cranking out two years of private equity so i ...,writing. criticizing. partying partying yeah.....,i've been described as 'all-american.' not sur...,...,"san francisco, california",NaN,straight,NaN,catholicism,m,NaN,no,70.0,single
2996,50,fit,NaN,rarely,never,graduated from college/university,i'm generally happy and typically spend my tim...,"i was raised with left-wing politics, pbs, bal...","i'm great with kids, dogs, cats and recycling....","gee, i don't know. . . that i'm smiling, that ...",...,"oakland, california",NaN,straight,has dogs,agnosticism,f,scorpio but it doesn&rsquo;t matter,no,63.0,single
2997,31,thin,vegetarian,socially,sometimes,NaN,NaN,"i like to move around, therefore my life entai...","having fun and not taking life too seriously, ...",my smile and hair.,...,"san francisco, california",NaN,straight,NaN,NaN,f,NaN,no,64.0,single
2998,31,athletic,mostly vegetarian,socially,sometimes,graduated from college/university,"i work with seniors and i love it, so believe ...",going down in flames.,being a charming first date.,i dress like an adorable idiot.,...,"walnut creek, california",NaN,straight,likes dogs and has cats,catholicism and laughing about it,f,aries and it&rsquo;s fun to think about,when drinking,62.0,single


## Types of Variables

There is a fundamental difference between variables like `age` and `height` which are measured on a numeric scale, and variables like `religion` and `pets` which are not.

Variables that can be measured on a numeric scale are called **quantitative variables** (or numerical variables).

Variables like `religion` or `pets` that place the observational units into a relatively limited set of categories are called **categorical variables**. We call each possible value of a categorical variable a "level". Levels are usually non-numeric.

Just because a variable happens to contain numbers does not necessarily make it "quantitative". For example, we could code the variable *Section* for the students in DATA 301 this quarter as 1 or 3, but Section is still a categorical variable; we could easily replace 1 with "first" or "earlier" and 3 with "second" or "later".  To see if a variable is quantitative, ask "would it make sense to take an average"? It doesn't really make sense to take an average of Section. On the other hand, if the variable is *number of classes enrolled in*, it does make sense to take an average---for example, "CP students take on average 4.2 classes per quarter"---even though this variable only takes discrete values like 0, 1, 2, 3, ...

Some variables do not fit neatly into the categorical/quantitative classification. For example, the variable `essay1` contains users' answers to the prompt "What I’m doing with my life". This variable is obviously not quantitative, but it is not categorical either because every user has a unique answer. In other words, this variable does not place each observation into a reasonable set of categories. We will group such variables into an "other" category.

Every variable can be classified into one of these three main **types**:
- quantitative,
- categorical,
- other.

The type of the variable dictates how we analyze that variable.

## Selecting Variables

Suppose we want to select the `age` column from the `DataFrame` above. There are three ways to do this.

1\. Access the column as you would a key in a `dict`.

In [19]:
df_okcupid["age"]

0       31
1       25
2       43
3       31
4       34
        ..
2995    24
2996    50
2997    31
2998    31
2999    60
Name: age, Length: 3000, dtype: int64

2\.  Use `.loc`, specifying both the rows and columns. (The colon `:` is Python shorthand for "all".)

In [20]:
df_okcupid.loc[:, "age"]

0       31
1       25
2       43
3       31
4       34
        ..
2995    24
2996    50
2997    31
2998    31
2999    60
Name: age, Length: 3000, dtype: int64

3\. Access the column as an attribute of the `DataFrame`.

In [21]:
df_okcupid.age

0       31
1       25
2       43
3       31
4       34
        ..
2995    24
2996    50
2997    31
2998    31
2999    60
Name: age, Length: 3000, dtype: int64

Method 3 (attribute access) is the most concise. However, it does not work if the variable name contains spaces or special characters, begins with a number, or matches an existing attribute of `DataFrame`. For example, if `df_okcupid` had a column called `info`, `df_okcupid.info` would not return the column because `df_okcupid.info` is already reserved for something else (`info` returns some basic information about the data frame).

Notice that when you select a single column, the result is no longer a `DataFrame`. It is instead a `Series`.

In [22]:
type(df_okcupid["age"])

pandas.core.series.Series

Notice that a `Series` is used here to store a single variable/column (across multiple observations/rows). In the previous section, we saw that a `Series` can also be used to store a single observation/row (across multiple variables/columns). To summarize,

- A `Series` stores one-dimensional data (i.e., a single observation/row or variable/column).
- A `DataFrame` stores two-dimensional data (i.e., both observations/rows and variables/columns).

To select multiple columns, you would pass in a _list_ of variable names, instead of a single variable name. For example, to select both `age` and `religion`, either of the two methods below would work (and produce the same result):

In [23]:
df_okcupid[["age", "religion"]]

,age,religion
0,31,buddhism
1,25,NaN
2,43,other and laughing about it
3,31,other and very serious about it
4,34,NaN
...,...,...
2995,24,catholicism
2996,50,agnosticism
2997,31,NaN
2998,31,catholicism and laughing about it


In [24]:
df_okcupid.loc[:, ["age", "religion"]]

,age,religion
0,31,buddhism
1,25,NaN
2,43,other and laughing about it
3,31,other and very serious about it
4,34,NaN
...,...,...
2995,24,catholicism
2996,50,agnosticism
2997,31,NaN
2998,31,catholicism and laughing about it


## Type Inference and Casting


Pandas tries to infer the type of each variable automatically. If every value in a column (except for missing values) is a number, then Pandas will treat that variable as quantitative. Otherwise, the variable is treated as categorical.

To determine the type that Pandas inferred, simply select that variable using the methods above and look for its `dtype`. A `dtype` of `float64` or `int64` indicates that the variable is quantitative.  For example, the `age` variable has a `dtype` of `int64`, so it is quantitative.

In [25]:
df_okcupid["age"]

0       31
1       25
2       43
3       31
4       34
        ..
2995    24
2996    50
2997    31
2998    31
2999    60
Name: age, Length: 3000, dtype: int64

On the other hand, the `religion` variable has a `dtype` of `object`, so `pandas` will treat it as categorical.

In [26]:
df_okcupid["religion"]

0                                buddhism
1                                     NaN
2             other and laughing about it
3         other and very serious about it
4                                     NaN
                      ...                
2995                          catholicism
2996                          agnosticism
2997                                  NaN
2998    catholicism and laughing about it
2999                                other
Name: religion, Length: 3000, dtype: object

Sometimes it is necessary to convert quantitative variables to categorical variables and vice versa. This can be achieved using the `.astype()` method of a `Series`. For example, to convert `age` to a categorical variable, we simply "cast" its values to strings. (More on casting later.)

In [27]:
df_okcupid["age"].astype(str)

0       31
1       25
2       43
3       31
4       34
        ..
2995    24
2996    50
2997    31
2998    31
2999    60
Name: age, Length: 3000, dtype: object

To save this as a column in the `DataFrame`, we assign it to a column called `age_cat`. Note that this column does not exist yet! It will be created at the time of assignment.

In [28]:
df_okcupid["age_cat"] = df_okcupid["age"].astype(str)

# Check that age_cat is a column in this DataFrame; see the last column
df_okcupid

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,offspring,orientation,pets,religion,sex,sign,smokes,height,status,age_cat
0,31,NaN,mostly vegetarian,socially,sometimes,graduated from college/university,"75% nice, 45% shy, 80% stubborn, 100% charming...",i'm a new nurse. it rules.,"multiple-choice questions, dancing.",it depends on the people.,...,might want kids,gay,likes cats,buddhism,f,taurus and it&rsquo;s fun to think about,no,67.0,single,31
1,25,average,NaN,socially,NaN,working on college/university,"i like trees, spending long periods of time co...","studying landscape horticulture, beekeeping, g...","wasting time, making breakfast, nesting",i have a lot of freckles,...,NaN,gay,NaN,NaN,m,sagittarius and it&rsquo;s fun to think about,no,66.0,single,25
2,43,curvy,NaN,rarely,never,graduated from masters program,NaN,NaN,NaN,NaN,...,has a kid,straight,likes dogs and has cats,other and laughing about it,f,leo and it&rsquo;s fun to think about,trying to quit,65.0,single,43
3,31,average,NaN,socially,never,NaN,"i am a seeker of laughs ,music ,magick good pe...",i strive to live life to the fullest and to tr...,i am good at my magic and weaving a world of i...,i am guessing y'all would notice my jewelry an...,...,doesn&rsquo;t want kids,gay,NaN,other and very serious about it,m,capricorn and it&rsquo;s fun to think about,trying to quit,70.0,single,31
4,34,NaN,NaN,socially,NaN,graduated from ph.d program,i've just moved here from london after finishi...,i'm doing a postdoc in psychology at stanford,NaN,NaN,...,NaN,gay,NaN,NaN,m,cancer but it doesn&rsquo;t matter,NaN,71.0,single,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,24,athletic,mostly anything,socially,sometimes,graduated from college/university,recent relocatee to san francisco. i'm writing...,cranking out two years of private equity so i ...,writing. criticizing. partying partying yeah.....,i've been described as 'all-american.' not sur...,...,NaN,straight,NaN,catholicism,m,NaN,no,70.0,single,24
2996,50,fit,NaN,rarely,never,graduated from college/university,i'm generally happy and typically spend my tim...,"i was raised with left-wing politics, pbs, bal...","i'm great with kids, dogs, cats and recycling....","gee, i don't know. . . that i'm smiling, that ...",...,NaN,straight,has dogs,agnosticism,f,scorpio but it doesn&rsquo;t matter,no,63.0,single,50
2997,31,thin,vegetarian,socially,sometimes,NaN,NaN,"i like to move around, therefore my life entai...","having fun and not taking life too seriously, ...",my smile and hair.,...,NaN,straight,NaN,NaN,f,NaN,no,64.0,single,31
2998,31,athletic,mostly vegetarian,socially,sometimes,graduated from college/university,"i work with seniors and i love it, so believe ...",going down in flames.,being a charming first date.,i dress like an adorable idiot.,...,NaN,straight,likes dogs and has cats,catholicism and laughing about it,f,aries and it&rsquo;s fun to think about,when drinking,62.0,single,31


In [29]:
# Check the type of age_cat is object
df_okcupid["age_cat"]

0       31
1       25
2       43
3       31
4       34
        ..
2995    24
2996    50
2997    31
2998    31
2999    60
Name: age_cat, Length: 3000, dtype: object